Added project subpages design and navigation
htw-imi-showtime/showtime-theme-2021 pull request #6
Opened 2021-01-11 01:30 UTC by Kaes3kuch3n

2021-01-11 13:14 UTC, tobihoffmann commented
Menu sieht top aus. Schön auch, dass es sticky ist!

2021-01-11 13:19 UTC, tobihoffmann requested changes
Der Abstand zwischen Project-Menu und dem ersten Content-Element sollte auf jeder Unterseite gleich sein, Also z.b `.project` ein padding-top geben und margin-top des ersten child elements resetten

2021-01-11 13:30 UTC, Kaes3kuch3n commented
@tobihoffmann Margin ist jetzt überall konstant 12rem 👍

2021-01-11 15:35 UTC, Kaes3kuch3n commented
Margin ist wieder kaputt, muss ich nochmal fixen 😅

2021-01-12 02:24 UTC, Kaes3kuch3n commented
@tobihoffmann Soo, dieses Mal sollte der Fix ein bisschen dauerhafter sein 👍 Ready for review

2021-01-16 10:00 UTC, tobihoffmann approved these changes

2021-01-16 10:00 UTC, merged